[mypy]
exclude = (?x)(
    ^docs/
    | ^examples/
    | ^tests/
    )
local_partial_types = True
; We target Python 3.9+ for type checking because modern mypy releases
; have dropped support for Python 3.8, even though our library supports 3.8.
python_version = 3.9
strict = True
warn_unreachable = True

[mypy-decouple]
follow_untyped_imports = True
ignore_missing_imports = True
